### ISSUE TITLE
little broken ascii

### ISSUE THREAD

**Issue by gibix** [emmawinston/thetinygallery#1]
Nexus 5, Android 6
![screenshot_20160207-172208](https://cloud.githubusercontent.com/assets/6577722/12873532/b55ec340-cdbf-11e5-920e-010e6911e854.png)

**Comment by emmawinston** [comment]
Hi! I assume this is something to do with the width at which different OSes render emojis (and ASCII, but here it looks like the issue in the top tweet at least is the width of the desert emoji, specifically), and am not entirely sure what, if anything, I can do to fix it, other than reducing the corpus of emojis the art is taken from to ones which are a consistent width across multiple OSes and devices (since I don't have access to an Android device I can't compile this myself, so would appreciate input from anyone who does!). 

I have a similar issue on iOS with the orange tent/camping emoji, which seems to render at about half the width of most of the other square emojis, despite the fact that the image itself is the same size. I've left it in the corpus for now because in desktop twitter it looks fine, but am still on the fence about removing it.

The difficulty is in repairing the spacing on one device/OS without breaking it on another. It's a peculiar little limitation I'm not sure how to get around (if only you could use CSS resets on Twitter!)

What I have done is slightly modified the top and bottom rows of the gallery code to try and get the corners of the gallery to look a little less uneven across multiple devices, since that was a noticeable bug in a number of screenshots I've been sent, including these.
